### ISSUE TITLE
The file LXC/chroot.md doesn't exist

### ISSUE THREAD

**Issue by oliverquynh** [vietkubers/kubernetes-training#18]
See the README.md file for more details

```markdown
 - [chroot](/LXC/chroot.md)
```

**Comment by truongnh1992** [comment]
@xuanquynh Thank you for your comment. We've just only outlined the contents. We will update it ASAP.
If you're willing to write a article about chroot, feel free to create a PR. We're highly appreciate it.

**Comment by oliverquynh** [comment]
@truongnh1992 Thanks! I haven't ever known it before. I will research it myself. :)
